[build]
  command = "npm install && npm run build"
  functions = "dist-lambda"

[dev]
    command = "npm start"
    port = 3000
    functionPort = "34567"
    targetPort = 3000
    autoLaunch = true

[[headers]]
  for="/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"